# Generic hooks for the whole repository
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^backend/alembic/
      - id: end-of-file-fixer
        exclude: ^backend/alembic/
      - id: check-yaml
        exclude: ^backend/alembic/
      - id: check-added-large-files
        exclude: ^backend/alembic/

# Backend (Python) specific hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3

    hooks:
      - id: ruff-check
        args: [ --fix, --config, backend/pyproject.toml]
        files: ^backend/
      - id: ruff-format
        args: [--config, backend/pyproject.toml]
        files: ^backend/
