services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - letterfeed_data:/data
    networks:
      - letterfeed_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - letterfeed_network

volumes:
  letterfeed_data:

networks:
  letterfeed_network:
    driver: bridge
